#define OK					0

#define DB_OPEN_ERR 		-100
#define DB_NO_HANDLES		-101
#define DB_INVALID_HANDLE	-102
#define DB_LOCKED_ON_OPEN	-103
#define DB_ACCESS_DENIED	-104
#define DB_CREATE_ERR		-105
#define DB_CLOSE_ERR		-106
#define DB_READONLY 		-107
#define DB_UPDATE_ERR		-108
#define DB_FILE_NAME_ERR	-109

#define DB_MEM_ERR			-110
#define DB_BAD_REC			-111
#define DB_NO_REC			-112
#define DB_REC_NOT_FOUND	-113
#define DB_REC_TOO_LONG 	-114
#define DB_NOT_DELETED		-115

#define DB_READ_ERR 		-121
#define DB_SEEK_ERR 		-122
#define DB_WRITE_ERR		-123
#define DB_DELETE_ERR		-124
#define DB_INSERT_ERR		-125
#define DB_LOCK_ERR 		-126
#define DB_UNLOCK_ERR		-127
#define DB_INVALID_RECORD	-128

#define DB_INVALID_FIELD	-130
#define DB_NOT_SUPPORTED	-131
#define DB_DEC_LNGTH		-132
#define DB_FLD_LNGTH		-133
#define DB_BAD_FLDNAME		-134
#define DB_MAX_FIELDS		-135
#define DB_INVALID_DATE 	-136
#define DB_INVALID_NUMBER	-137
#define DB_INVALID_CHAR 	-138
#define DB_INVALID_NUM		-139
